name: Documentation

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/checkout/issues/1471
      # Clobber local unannotated tag
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags --force
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: docs
          cache-environment: true
          post-cleanup: 'all'
          init-shell: bash
          create-args: >
            python=3.12
            pip
            cartopy
            matplotlib
            sphinx
            sphinx-book-theme
            sphinx-copybutton
            sphinx-design
            sphinx-inline-tabs
            sphinx_rtd_theme
            sphinx-tabs
            docstring_parser
            fsspec
            h5netcdf
            jinja2
            myst-nb
            netCDF4
            numba
            numpy
            requests
            typer
            xarray
            pytest
            pytest-cov
            sympy
            beautifulsoup4
            shapely
            geopandas
            pyinterp<2026.2.0
            dask
      - name: Install package (for autodoc)
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Install AVISO Client
        shell: bash -l {0}
        run: |
          pip install altimetry-downloader-aviso
      - name: Setup AVISO credentials
        run: |
          echo "machine tds-odatis.aviso.altimetry.fr login ${{ secrets.AVISO_USER }} password ${{ secrets.AVISO_PASSWORD }}" > ~/.netrc
      # Cached retrieval of L2_LR_SSH data
      - name: Restore cached sample data for L2_LR_SSH
        uses: actions/cache@v4
        id: restore_samples_l2_lr_ssh
        with:
          path: docs/implementations/data_l2_lr_ssh
          key: samples-${{ hashFiles('docs/implementations/scripts/pull_data_l2_lr_ssh.py') }}
      - name: Pull L2_LR_SSH Samples
        if: steps.restore_samples_l2_lr_ssh.outputs['cache-hit'] != 'true'
        shell: bash -l {0}
        run: |
          set -e
          python docs/implementations/scripts/pull_data_l2_lr_ssh.py
      - name: Cache L2_LR_SSH data
        uses: actions/cache/save@v4
        if: steps.restore_samples_l2_lr_ssh.outputs['cache-hit'] != 'true'
        with:
          path: docs/implementations/data_l2_lr_ssh
          key: samples-${{ hashFiles('docs/implementations/scripts/pull_data_l2_lr_ssh.py') }}
      # Cached retrieval of L3_LR_SSH data
      - name: Restore cached sample data for L3_LR_SSH
        uses: actions/cache@v4
        id: restore_samples_l3_lr_ssh
        with:
          path: docs/implementations/data_l3_lr_ssh
          key: samples-${{ hashFiles('docs/implementations/scripts/pull_data_l3_lr_ssh.py') }}
      - name: Pull L3_LR_SSH Samples
        if: steps.restore_samples_l3_lr_ssh.outputs['cache-hit'] != 'true'
        shell: bash -l {0}
        run: |
          set -e
          python docs/implementations/scripts/pull_data_l3_lr_ssh.py
      - name: Cache L3_LR_SSH data
        uses: actions/cache/save@v4
        if: steps.restore_samples_l3_lr_ssh.outputs['cache-hit'] != 'true'
        with:
          path: docs/implementations/data_l3_lr_ssh
          key: samples-${{ hashFiles('docs/implementations/scripts/pull_data_l3_lr_ssh.py') }}
      # DOC BUILD
      - name: Build Sphinx HTML
        shell: bash -l {0}
        run: |
          sphinx-build -T -b html docs build -W
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
          name: docs

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy stable docs
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: docs
          target_branch: gh-pages
          folder: stable
